version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm cache clean --force
        - rm -rf node_modules
        - rm -rf dist
        - npm install
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:  
    paths:
      - node_modules/**/*  
